services:
  db:
    ports: !reset []
    restart: unless-stopped

  data_load:
    restart: on-failure

  data_quality_analysis:
    restart: on-failure

  data_research:
    restart: on-failure

  visualization:
    restart: on-failure

  web:
    restart: unless-stopped
