#cloud-config
package_update: false

runcmd:
  - fallocate -l 2G /swapfile
  - chmod 600 /swapfile
  - mkswap /swapfile
  - swapon /swapfile
  - echo '/swapfile none swap sw 0 0' >> /etc/fstab

  - dnf install -y git

  - wget -qO- https://get.docker.com/ | sh
  - systemctl enable --now docker
  - usermod -aG docker opc

  - mkdir -p /opt/app
  - git clone https://github.com/sviathumeniuk/open-data-ai-analytics.git /opt/app

  - |
    cat <<EOF > /opt/app/.env
    SQLITE_DB_PATH=/workspace/data/analytics.db
    TABLE_NAME=vat_registry
    CSV_PATH=/workspace/raw/pdv_actual_28-08-2019.csv
    FIGURES_ROOT=/workspace/reports/figures
    QUALITY_REPORT_PATH=/workspace/reports/data_quality/latest.json
    RESEARCH_REPORT_PATH=/workspace/reports/data_research/summary.json
    ECONOMIC_EVENT_YEAR=2014
    EOF

  - mkdir -p /opt/app/data
  - cd /opt/app && docker compose up -d --build

  - logger 'Cloud-init FINISHED: Analytics project is live!'