apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-web
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      initContainers:
        - name: pipeline
          image: ghcr.io/sviathumeniuk/open-data-ai-analytics:sha-dbc396dd57b26c23a02d600a8d3b015b5dcf8250
          command: ["python", "pipeline/run_all.py"]
          env:
            - name: SQLITE_DB_PATH
              value: "/workspace/data/analytics.db"
            - name: CSV_PATH
              value: "/workspace/raw/pdv_actual_28-08-2019.csv"
          volumeMounts:
            - name: storage
              mountPath: /workspace/data
      containers:
        - name: web
          image: ghcr.io/sviathumeniuk/open-data-ai-analytics:sha-dbc396dd57b26c23a02d600a8d3b015b5dcf8250
          ports:
            - containerPort: 8000
          env:
            - name: SQLITE_DB_PATH
              value: "/workspace/data/analytics.db"
          volumeMounts:
            - name: storage
              mountPath: /workspace/data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: analytics-data-pvc
